"""
train_llm.py — Baseline LLM Training Script

Trains the standard autoregressive baseline using causal language modeling 
(Next-Token Prediction) on the raw TinyStories dataset.
"""

import os
import sys
import time
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
import torch.optim as optim

# Add the current directory to sys.path so Python can find the 'LLM' folder
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from dataset_preprocess import get_or_train_tokenizer
from LLM import config
from LLM.model import BaselineLLM

class StandardLLMDataset(Dataset):
    """Chunks the raw text into contiguous sliding windows for standard causal modeling."""
    def __init__(self, raw_text_path, tokenizer, seq_len):
        print(f"Reading and tokenizing {raw_text_path} for standard LLM...")
        with open(raw_text_path, "r", encoding="utf-8") as f:
            raw_text = f.read()
            
        # Clean text
        raw_text = raw_text.replace('\n', ' ').strip()
        tokens = tokenizer.encode(raw_text).ids
        
        self.seq_len = seq_len
        self.samples = []
        
        # We need seq_len + 1 tokens per chunk so we can split into (Inputs) and (Targets)
        chunk_size = seq_len + 1
        for i in range(0, len(tokens) - chunk_size, chunk_size):
            self.samples.append(torch.tensor(tokens[i:i+chunk_size], dtype=torch.long))
            
        print(f"Created {len(self.samples)} training chunks of length {seq_len}.")
            
    def __len__(self):
        return len(self.samples)
        
    def __getitem__(self, idx):
        return self.samples[idx]

def count_all_parameters(model):
    return sum(p.numel() for p in {id(p): p for p in model.parameters()}.values())

def main():
    device = config.DEVICE
    print(f"Using device: {device}")
    
    # Reuse the exact same tokenizer generated by the GSC pipeline
    tokenizer = get_or_train_tokenizer(raw_text_path=config.DATASET_PATH, vocab_size=config.VOCAB_SIZE)
    
    dataset = StandardLLMDataset(config.DATASET_PATH, tokenizer, seq_len=config.MAX_SEQ_LEN)
    dataloader = DataLoader(dataset, batch_size=config.BATCH_SIZE, shuffle=True, drop_last=True)
    
    model = BaselineLLM(
        vocab_size=config.VOCAB_SIZE, 
        d_model=config.D_MODEL, 
        n_heads=config.N_HEADS, 
        num_layers=config.NUM_LAYERS, 
        dim_feedforward=config.DIM_FEEDFORWARD, 
        max_seq_len=config.MAX_SEQ_LEN
    ).to(device)
    
    unique_params = count_all_parameters(model)
    print(f"\nBaseline LLM Parameters: {unique_params:,}\n")
    
    optimizer = optim.Adam(model.parameters(), lr=3e-4)
    
    os.makedirs(config.BASE_DIR, exist_ok=True)
    
    print("="*50)
    print("🚀 STARTING BASELINE LLM TRAINING")
    print("="*50)
    
    for epoch in range(1, config.EPOCHS + 1):
        model.train()
        total_loss = 0.0
        start_time = time.time()
        
        for batch_idx, batch in enumerate(dataloader):
            batch = batch.to(device)
            
            inputs = batch[:, :-1]  # All tokens except the last
            targets = batch[:, 1:]  # All tokens except the first
            
            optimizer.zero_grad()
            logits = model(inputs)
            
            # Flatten for Cross Entropy
            loss = F.cross_entropy(logits.reshape(-1, config.VOCAB_SIZE), targets.reshape(-1))
            
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            
        avg_loss = total_loss / len(dataloader)
        elapsed = time.time() - start_time
        
        print(f"Epoch {epoch:02d}/{config.EPOCHS} | Time: {elapsed:.2f}s | Loss: {avg_loss:.4f} | Perplexity: {torch.exp(torch.tensor(avg_loss)):.2f}")

    print("\n✅ Baseline Training Complete. Saving model...")
    torch.save(model.state_dict(), os.path.join(config.BASE_DIR, "baseline_llm.pt"))

if __name__ == "__main__":
    main()